Add the South Tyrol public transport
schildbach/public-transport-enabler pull request #189
Opened 2018-02-16 18:43 UTC by danielegobbetti

The service is provided by the province of Bolzano/Bozen (in northern Italy).
The data are available under a CC0-license, see http://dati.retecivica.bz.it/de/dataset/southtyrolean-public-transport

The tests were adapted from the LinzAdapter ones.

I verified that the data match with reality since I live there, please be  aware that I only tested by building the android app Transportr and using my fork of the enabler library.
As I am by no means an expert of EFA, I don't know what the different setters do, if there are further tests I should perform I will happily follow instructions :-)

2018-02-17 16:12 UTC, danielegobbetti commented
@grote a question for you since I noticed you are active here. I should wait until this is merged and transportr is updated to include the right commit, before opening the PR in transportr for its inclusion, right?

2018-02-17 16:18 UTC, grote commented
@danielegobbetti I think it makes sense to wait for this to get merged. Then you can prepare a PR for Transportr (that also bumps the commit ID of PTE).

2018-10-23 06:53 UTC, danielegobbetti commented
@schildbach FYI my locally compiled Transportr is still working with the new provider, do you want me to test it with Öffi as well before merging?

2025-01-23 02:23 UTC, Amyashleygomez requested changes
Update 2 my name

2025-02-24 12:52 UTC, valerio-bozzolan commented
Hi @danielegobbetti - is the API offline now? :thinking: 

http://dati.retecivica.bz.it/de/dataset/southtyrolean-public-transport

2025-02-24 13:36 UTC, danielegobbetti commented
> Hi @danielegobbetti - is the API offline now? 🤔
> 
> http://dati.retecivica.bz.it/de/dataset/southtyrolean-public-transport

Looks like it is, I guess it could have been replaced by some service at opendatahub.com
Anyway I don't believe this PR has any chance of working after 7 years, and I'm sure someone more knowledgeable than me can have better luck by starting fresh from master.

2025-02-24 13:36 UTC, closed without merging